### PR TITLE
make cmake

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by jiskattema** [comment]
Hi Gijs, thanks for working on the code! You are preparing the code to be used in science case 4? Some comments on your changes:
* if you switch to cmake (no problem), please remove the current 'Makefile'
* Why are you linking to Cuda? I dont think it hurts (slows down) the code, but we're not depending on it

**Comment by gijzelaerr** [comment]
psrdada is linked to cuda:

```Scanning dependencies of target fake
[ 83%] Building C object CMakeFiles/fake.dir/src/fake.c.o
[100%] Linking C executable fake
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcutil_cuda.o): In function `ipc_alloc_cuda':
(.text+0x80): undefined reference to `cudaSetDevice'
(.text+0xe2): undefined reference to `cudaIpcOpenMemHandle'
(.text+0x12e): undefined reference to `cudaMalloc'
(.text+0x13f): undefined reference to `cudaIpcGetMemHandle'
(.text+0x14a): undefined reference to `cudaGetErrorString'
(.text+0x183): undefined reference to `cudaGetErrorString'
(.text+0x1e3): undefined reference to `cudaGetErrorString'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcutil_cuda.o): In function `ipc_disconnect_cuda':
(.text+0x245): undefined reference to `cudaIpcCloseMemHandle'
(.text+0x25b): undefined reference to `cudaGetErrorString'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcutil_cuda.o): In function `ipc_dealloc_cuda':
(.text+0x297): undefined reference to `cudaSetDevice'
(.text+0x29f): undefined reference to `cudaFree'
(.text+0x2b3): undefined reference to `cudaGetErrorString'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcutil_cuda.o): In function `ipc_zero_buffer_cuda':
(.text+0x2ea): undefined reference to `cudaMemset'
(.text+0x303): undefined reference to `cudaGetErrorString'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcutil_cuda.o): In function `__cudaUnregisterBinaryUtil()':
(.text+0x8): undefined reference to `__cudaUnregisterFatBinary'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcutil_cuda.o): In function `__sti____cudaRegisterAll()':
(.text.startup+0xc): undefined reference to `__cudaRegisterFatBinary'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcio.o): In function `ipcio_write':
(.text+0x71f): undefined reference to `cudaMemcpy'
(.text+0x72c): undefined reference to `cudaDeviceSynchronize'
(.text+0x803): undefined reference to `cudaSetDevice'
(.text+0x812): undefined reference to `cudaGetErrorString'
(.text+0x876): undefined reference to `cudaGetErrorString'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpsrdada.a(ipcio.o): In function `ipcio_read':
(.text+0xf6a): undefined reference to `cudaMemcpy'
(.text+0xf77): undefined reference to `cudaDeviceSynchronize'
(.text+0x1033): undefined reference to `cudaGetErrorString'
(.text+0x10a3): undefined reference to `cudaSetDevice'
(.text+0x10b2): undefined reference to `cudaGetErrorString'
collect2: error: ld returned 1 exit status
CMakeFiles/fake.dir/build.make:95: recipe for target 'fake' failed
make[2]: *** [fake] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/fake.dir/all' failed
make[1]: *** [CMakeFiles/fake.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jiskattema** [comment]
Ok, that is a good reason. Not sure who is using psrdada-cuda; maybe we can drop it there, too.

**Comment by jiskattema** [comment]
What happened to the compiler flags? Originally i had 
```CFLAGS += -O3 -g0 -march=native -fstrict-aliasing``` which is needed for decent performance. Will cmake pick these up from the environment during build?
Please add a note to the README on this.

**Comment by gijzelaerr** [comment]
strict-aliasing is implicitly enabled by -02 and higher. If you compile with `CMAKE_BUILD_TYPE=release` these are the default flags:

```cc -march=native -O2 -pipe -O3 -DNDEBUG``` which as far as I know do what you want.

**Comment by jiskattema** [comment]
Ok, nice i didn't know that. Can you add that explanation to the README ?

**Comment by gijzelaerr** [comment]
i'm not sure if that is a useful, since this is  just default cmake behavior. I prefer not to replicate the cmake documentation :)

I think just adding CMAKE_BUILD_TYPE=release to the doc might be helpful.

**Comment by jiskattema** [comment]
I still prefer making the compiler flags explicit. On my system (fedora), it defaults to ```-O2```, without the ```-march=native```. Worst case, that disables all SIMD / AVX / SSE instructions and that could mean a significant performance hit for some of the pipeline. Although, this code (ringbuffer) does not do floating point math or large memcpy's so the impact here will be less..

**Comment by gijzelaerr** [comment]
there you go

**Pull request merged**
